### ISSUE TITLE
Duplicated declarations

### ISSUE THREAD

**Issue by sonjli** [mirko-bianco/FidoLib#44]
In `Fido.VirtualQuery.Attributes` some attributes are declared duplicated as in `Fido.VirtualStatement.Attributes`.

This causes a problem in `Fido.VirtualQuery` where they are used both: the RTTI loop on attributes does not recognize the right attribute class in line 188, because the RTTI informations about attributes are different for the two declarations.

The attributes with this defect are:
`PagingLimitAttribute`
`PagingOffsetAttribute`
`SqlInjectAttribute`

A possible solution is to remove attribute declaration from `Fido.VirtualQuery.Attributes` or to create a common `Fido.VirtualStatement.CommonAttributes` with the three attributes.

**Comment by mirko-bianco** [comment]
I'd prefer to have two separate sets, like VirtualQueryPagingLimitAttribute and VirtualStatementPagingLimitAttribute and so on.
